### PR TITLE
Upgraded to FodyCecil 2.0

### PR DESCRIPTION
**Pull request by andyhoyle**
Upgraded to Fody 2 and Removed MonoCecil and replace with FodyCecil

### CODE REVIEW

**Comment by chrissingh** [comment]
Any status on merging this pull request and releasing via Nuget? Needed to work with Fody 2.0.

**Comment by SimonCropp** [comment]
Sorry missed this one. I will smoke test and deploy today

**Comment by brianstringfellow** [comment]
When will the NuGet package get updated? It is still at 0.9.0.6.

**Comment by ChaseFlorell** [comment]
Hey All, hoping to see this on Nuget soon!

**Comment by igorushi** [comment]
@SimonCropp , @citizenmatt , can you please push it to Nuget? I can't update fody since I depend on this one...

**Pull request merged**
