### PR TITLE
Allow global application of method decorations by attribute

### PR DESCRIPTION
**Pull request by alansingfield**
This is a resolution for feature request:
[https://github.com/Fody/MethodDecorator/issues/17](https://github.com/Fody/MethodDecorator/issues/17)

This allows you to globally apply a method decorator to all classes in a namespace or group of namespaces, in a similar manner to PostSharp.

To use this:
1. Create an attribute which implements IMethodDecorator and IAspectMatchingRule
`	[AttributeUsage( AttributeTargets.Method 
				   | AttributeTargets.Constructor
				   | AttributeTargets.Class 
				   | AttributeTargets.Module 
				   | AttributeTargets.Assembly,
				   AllowMultiple=true)]
	public class MatchingDecoratorAttribute : Attribute, IAspectMatchingRule, IMethodDecorator
`

2. Apply this attribute at the assembly level:

`[assembly: DerivedMatchingDecorator(AttributeTargetTypes="SimpleTest.DerivedMatchingAssembly.*")]`

3. Any classes in the namespace SimpleTest.DerivedMatchingAssembly will have the decorator applied to them.

The AttributeTargetTypes doesn't yet support a comma-separated list of types (like PostSharp), but you can apply the attribute multiple times using AllowMultiple=true to work around this for now.

### CODE REVIEW

**Comment by alansingfield** [comment]
Hello Alexey,

 

Thanks for merging in my changes.

 

Can you tell me when you will be refreshing the Nuget package please?


Thanks,

 

Alan.

**Comment by smotnam** [comment]
@alansingfield this is not working for me, I created an interface IAspectMatchingRule, my custom attribute extends it. And applied the attribute at the custom level. Could you please tell me if I need to do anything else. Thanks

**Comment by alansingfield** [comment]
Hello @smotnam, this has not been merged into the Nuget package yet so you'd need to get the latest source and use that. You could then debug the matching process and find out what has gone wrong. There are a set of tests that you can try, to see the intended operation of IAspectMatchingRule. Please let me know if you find a bug.

Thanks,

Alan.

**Comment by smotnam** [comment]
@alansingfield Thank you for responding.
I got latest code and used it, however IAspectMatchingRule didnt work. I declared something like this [assembly: MethodEntryExit(AttributeTargetTypes="SimpleTest.DerivedMatchingAssembly.*")] with in the same Assembly where I have the attribute but still OnEntry() is not getting executed for every method. I will try to debug and see if I did any mistake or if there is a bug.
Thanks

**Pull request merged**
